### ISSUE TITLE
缺少框架啊 运行不起来。

### ISSUE THREAD

**Issue by xuezhanying** [zhongwuzw/WebBrowser#1]
缺少五个框架啊 <CocoaLumberjack/CocoaLumberjack.h> 像AFN  HUD 了

**Comment by zhongwuzw** [comment]
@xuezhanying 项目依赖[Carthage](https://github.com/Carthage/Carthage),运行方法参见[Readme](https://github.com/zhongwuzw/WebBrowser#usage---用法)用法部分。

**Comment by xuezhanying** [comment]
恩  Run command `carthage update --platform iOS` ，你的意思是 在下载 Carthage-master 这个文件，这个下载打开之后里面有三个文件 打开哪个啊？Carthage.workspace,Carthage.xcodeproj,XCDBLD.xcodeproj

**Comment by xuezhanying** [comment]
你的 QQ 多少 咱们加上详聊，我的是935156938

**Comment by xuezhanying** [comment]
Run command `carthage update --platform iOS`  这第二句 是什么意思。

**Comment by zhongwuzw** [comment]
1. 首先安装`carthage`，参考：[https://github.com/Carthage/Carthage#installing-carthage](https://github.com/Carthage/Carthage#installing-carthage)
2. 在`WebBrowser`项目目录执行`carthage update --platform iOS`即可。

**Comment by GongHongORzm** [comment]
哈哈哈哈  我解决了    没看清步骤

**Comment by xuezhanying** [comment]
你怎么解决的，给我发一份代码 我的QQ 号是 935156938

**Comment by FuckUmei** [comment]
lz你好。。已经执行了carthage update --platform iOS 也成功了， 但是项目中没有看到相应的framework

**Comment by zhongwuzw** [comment]
@FuckUmei , 项目运行出错么？`carthage`操作成功后，`framework`会在如下目录：
<img width="822" alt="qq20171130-202346 2x" src="https://user-images.githubusercontent.com/5061845/33430699-6e70fd66-d60c-11e7-809f-02af2ff7ea5d.png">

**Comment by FuckUmei** [comment]
哦 好像是 carthage失败了。。现在只有AFNetwork、Mantle、其他的都没有update下来。。我再试试。。感谢lz
