### ISSUE TITLE
无法加载需要身份验证的网页

### ISSUE THREAD

**Issue by whatsbug** [zhongwuzw/WebBrowser#11]
老哥我发现有些需要身份验证的网页是无法加载的，比如这个：https://ph.6632888.com/ph2.html
用Safari是可以的，不知道是什么原因，还望指教，蟹蟹啦。

**Comment by zhongwuzw** [comment]
@whatsbug 这个网页用了`basicAuthentication`,`UIWebView`默认是无法弹出输入用户名、密码的弹窗。
我提交了一个测试[commic](https://github.com/zhongwuzw/WebBrowser/commit/a7dffbc07ae7acbe0556658c5c5afb90f9d7e709)，你可否验证一下？我没有这样的网站用户名、密码可以验证。

**Comment by zhongwuzw** [comment]
@whatsbug ，建议学习一下`HTTP`协议认证的部分，这些都是由后端控制的。

**Comment by whatsbug** [comment]
好的~ 三克油。。
