### ISSUE TITLE
一个网址本地缓存的问题。

### ISSUE THREAD

**Issue by CXTretar** [zhongwuzw/WebBrowser#14]
测试Demo时发现，假如第一次安装后未打开任何新网址，在下次启动Demo时，会出现首页加载白屏，发现加载的网址是http://localhost:0/about/sessionrestore?history={"history":["about:homepage"],"currentPage":0} ； 作者大大有时间可以说明一下用 GCDWebServer 缓存网页浏览记录的原理么？

**Comment by zhongwuzw** [comment]
@CXTretar 你好，这个bug是必现的么？请提供`iOS`版本、设备等，我定位一下。

**Comment by CXTretar** [comment]
@zhongwuzw 应该是必现的，因为我自己的项目中使用同样的方式start，也出现问题，我重新下载master测试确定一下，测试用的模拟器iPhone 6 iOS 11.2. 真机 iPhone 5s iOS 10.2 。

**Comment by zhongwuzw** [comment]
@CXTretar ,我这边没法复现，根据你提供的`URL`，端口号显示为0，也就是`_options`赋值的时候6800没赋值上，你这边能在这打个断点调试一下么？

```
// GCDWebServer.m
- (BOOL)_start:(NSError**)error {
  GWS_DCHECK(_source4 == NULL);

  NSUInteger port = [_GetOption(_options, GCDWebServerOption_Port, @0) unsignedIntegerValue];
```

**Comment by CXTretar** [comment]
@zhongwuzw 重新下载新的项目运行是没有问题的，但是早上我测试了很多遍一直有这个问题，这个会跟网络环境有关系？

**Comment by CXTretar** [comment]
![image](https://user-images.githubusercontent.com/17959278/41398104-cc45a556-6fe8-11e8-9f94-4e9b066033fd.png)
这个错误shi是怎么造成的

**Comment by CXTretar** [comment]
无法重现了，应该是模拟器出的异常。
