### ISSUE TITLE
项目无法运行

### ISSUE THREAD

**Issue by bxjxxyy** [zhongwuzw/WebBrowser#19]
使用的carthage方式，成功update后，xcode编译通过。
运行时在启动页面报错 dyld: Library not loaded   Reason: image not found   涉及AFNNetWordking.framework,GCDWebServers.framework,Mantle.framework.
将涉及的framework添加到Embedded Binaries内后，再运行，在启动页面时报错。如下图

![image](https://user-images.githubusercontent.com/26214176/46590412-97543580-cae5-11e8-9c0f-aab876f80d63.png)

请问是哪里没有弄对?

**Comment by zhongwuzw** [comment]
@bxjxxyy 我觉得应该是`Xcode`的问题，你可以试一下下面的两种方式，看是否能解决问题。

1. [Clean and Rebuild](https://stackoverflow.com/a/46028623/3552084)
2. [Move frameworks to Embedded Binaries](https://stackoverflow.com/a/42185158/3552084)

**Comment by bxjxxyy** [comment]
我把所有报错 image not found的framework都添加到Embedded Binaries，并从LInked FrameWork and Libraries删除了。然后可以运行起来了。
但是运行起来后，不论打开什么网址，页面上看起来就是一个显示的不完全的百度首页。

**Comment by zhongwuzw** [comment]
@bxjxxyy 奇怪，你方便把工程打个包发出来么，我看一下原因。

**Comment by bxjxxyy** [comment]
发到你资料里面的QQ邮箱了。邮件名是 bxjxxyy WebBrowser。

**Comment by zhongwuzw** [comment]
@bxjxxyy 你是在运行`carthage`前执行了`transfer-carthage-to-cocoapods.sh`脚本么？你发过来的项目中没有`Run Script`部分，我理解应该是你这边把这个配置移除了，导致crash：
<img width="829" alt="image" src="https://user-images.githubusercontent.com/5061845/46646023-6265e280-cbba-11e8-8fa8-28135562f485.png">

关于百度首页问题，我已经提交了commit, 请参见最新的`master`代码，感谢`Issue`.

**Comment by bxjxxyy** [comment]
之前可能是错误的执行过那个sh。现在重新下载了master代码，一切正常了。十分感谢。
