### ISSUE TITLE
压根打不开啊 老哥！

### ISSUE THREAD

**Issue by GongHongORzm** [zhongwuzw/WebBrowser#2]
**# 各种库缺少，然后我自己创建了podfile，下载了那些库，还是运行不了哎。
望回复老哥。**

**Comment by zhongwuzw** [comment]
使用的[Carthage](https://github.com/Carthage/Carthage)，未使用`CocoaPods`。

**Comment by GongHongORzm** [comment]
*** Fetching Mantle
*** Fetching CocoaLumberjack
*** Fetching AFNetworking
*** Fetching SDWebImage
*** Fetching GCDWebServer
*** Fetching MBProgressHUD
*** Checking out GCDWebServer at "3.4.2"
*** Downloading AFNetworking.framework binary at "3.1.0"
*** Checking out AFNetworking at "3.1.0"
*** Checking out MBProgressHUD at "1.1.0"
*** Checking out SDWebImage at "4.2.2"
*** Checking out CocoaLumberjack at "3.3.0"
*** Downloading Mantle.framework binary at "2.1.0"
*** xcodebuild output can be found in /var/folders/9f/pmrx8jqs5lb0850fszpbh3yr0000gp/T/carthage-xcodebuild.vcNK5H.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/yyliu/Downloads/WebBrowser-master/Carthage/Checkouts/AFNetworking/AFNetworking.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

在 2017-11-29 14:30:13，"Wu Zhong" <notifications@github.com> 写道：


使用的Carthage，未使用CocoaPods。
