### ISSUE TITLE
作者你好，随便找一个可以播放视频的网站，打开以后，返回桌面，会出现崩溃

### ISSUE THREAD

**Issue by smilexuetao** [zhongwuzw/WebBrowser#28]

**Comment by zhongwuzw** [comment]
Can you provide the crash log?

**Comment by smilexuetao** [comment]
> Can you provide the crash log?

你运行到手机上，然后打开一个视频网站，按Home键，保持数据线连接，就会出现 WebThread (11): EXC_BAD_ACCESS (code=1, address=0x1)

**Comment by zhongwuzw** [comment]
我这边无法复现，请提供设备环境信息。你这边安装后，不要进入调试模式运行app。
