### ISSUE TITLE
大佬，考虑支持一波pod啊

### ISSUE THREAD

**Issue by LixinQian** [zhongwuzw/WebBrowser#8]

**Comment by zhongwuzw** [comment]
@LixinQian ，项目运行可以使用`CocoaPods`了。

**Comment by LixinQian** [comment]
CocoaPods上拉下来好多文件找不到！CocoaPods是不是支持的不全啊？

**Comment by zhongwuzw** [comment]
执行`pod install`时有报错么？是按照这个[步骤](https://github.com/zhongwuzw/WebBrowser#usage---用法)走的么？

**Comment by LixinQian** [comment]
执行pod install时没有报错，执行完之后运行不起来，好多文件找不到

**Comment by LixinQian** [comment]
应该是之前在使用Carthage时，它可以把依赖的库都编译成framework，你直接应用了framework里的文件，而CocoaPods 没有找到对应的文件，报错，运行不了！

**Comment by zhongwuzw** [comment]
@LixinQian , 是的，我写一个脚本处理一下，移除`Carthage`的部分。

**Comment by zhongwuzw** [comment]
@LixinQian 我已经更新了一个脚本，目的是移除`Carthage`相关依赖，在执行`pod install`之前，需先执行该脚本。可参考[安装步骤](https://github.com/zhongwuzw/WebBrowser#usage---%E7%94%A8%E6%B3%95).

**Comment by LixinQian** [comment]
666666
